library  identifier: 'jenkins-shared-lib@main',
         retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/falanges/jenkins-shared-lib.git'])

pipeline {
    agent any
    environment {
      RELEASE='20.04'
    }
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
        stage('Build') {
            environment {
                VERSION_SUFFIX = getVersionSuffix()
            }
            steps {
                echo "Building version: ${VERSION} with suffix: ${VERSION_SUFFIX}"
            }
        }
    }
}